#! /bin/sh

set -e

cargo fmt --all --check

cargo clippy --workspace -- -D warnings         \
    -W clippy::complexity                       \
    -W clippy::correctness                      \
    -W clippy::nursery                          \
    -W clippy::perf                             \
    -W clippy::style                            \
    -W clippy::suspicious

cargo test --workspace
