[package]
name = "logger"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
chrono = "0.4.23"
once_cell = "1.17.0"

[features]
logger = []
